version: "3.8"
services:
  mongodb:
    image: mongo:4.4.14-focal
    container_name: oobir.mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=microservice
      - MONGO_INITDB_ROOT_PASSWORD=A1d2r3i4a5n!
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    expose: [56808]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27018/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb-data:
